### ISSUE TITLE
Error : FileNotFoundError

### ISSUE THREAD

**Issue by jacob2020baklas** [EngineerDanny/apk-downloader#3]
it does trow this error : 

**$: python3 main.py com.example.exmp**

 Hello, Welcome to APK Downloader 🙌 !!! 
 Getting download link... 
 Downloading APK 🚀🚀🚀 
 Traceback (most recent call last):
   File "/tmp/apk-downloader/main.py", line 193, in <module>
     main()
   File "/tmp/apk-downloader/main.py", line 173, in main
     with open(output_file, 'wb') as f:
 FileNotFoundError: [Errno 2] No such file or directory: 'output/app_name.apk'

**Comment by mueller-peter** [comment]
you can fix it with:
```
mkdir output
```

re-run the script and it works :)
